# Generated by Django 2.2.6 on 2019-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classs',
            name='criteria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.75, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='classs',
            name='total_days',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
