# Generated by Django 2.2.6 on 2019-10-03 02:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=250)),
                ('note_content', tinymce.models.HTMLField(verbose_name='Content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classs.Classs')),
            ],
        ),
    ]
