# Generated by Django 2.2.6 on 2019-10-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='assignment',
        ),
    ]
