# Generated by Django 2.2.6 on 2019-10-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
        ('assignments', '0002_remove_choice_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classs.Classs'),
        ),
    ]
